apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dpuk

bases:
- ../../base

patchesStrategicMerge:
  - wiki.yml
  

patches:
- target:
    kind: Application
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: serp-wiki-dpuk