apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-discourse99
  namespace: hiru-mgmt-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  destination:
    name: in-cluster
    namespace: simon-test765
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.0.0
    chart: discourse
    helm:
      parameters:
        - name: auth.email
          value: user@user.com
        - name: auth.password
          value: password
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostname
          value: discourse.demo.k8s.hiru.swan.ac.uk
        - name: ingress.ingressClassName
          value: nginx
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

