apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-app-dev
  namespace: hiru-mgmt-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook-dev
    name: in-cluster
  project: default
  source:
    path: kustomized_helm/overlays/dev
    repoURL: https://github.com/d0-labs/argocd-app-of-apps-child-guestbook
    targetRevision: HEAD
    plugin:
      name: kustomized-helm